services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB= postDB
      - POSTGRES_USER= postgres
      - POSTGRES_PASSWORD= "123456"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8000:8080"
